before_install:
  - wget https://github.com/gohugoio/hugo/releases/download/v0.25.1/hugo_0.25.1_Linux-64bit.deb
  - sudo dpkg -i hugo_0.25.1_Linux-64bit.deb

script:
  - ./deploy.sh

env:
  global:
  - secure: jFm76z5AkfXp4t1dahK0Mmgtdu05yNiJMc/CRyU1hDpIoMYhA7vQH9afe993aNBCiUXP+qLXPtP1XyVX9Vl5rSpUOhsw4bNl2HCXohlq6rQ5HhSuHVokiupmyt51IMA6PX6MJH3imd+RQcwYBdKQ4VHFVi9NTRpto3bXfCBDecTDj88k7hAcRfuqcxvY2b0GWz6dgmSYmQt/lBdKm47lbibskWaIs82P7xU1yZykUKVAKbXxTOxn2xgfErZxXpdlpyz3xYdf0ig62avS7arzc7uVfxx2lonZ75P+AzgPhKz5fTy0LKtMPUK+x8ur2Tmh3EnoB27jaKe9wqiHQJUPRNeR1PMMpxVR1coSyieHtwRyS3/ul/g9UtGuG88QENoyK6G0xqyou+WimWihOB7gR2D6J46r2+3V9/Lm/8EnXZF/Tvj1g7MVK+fvJgN9Sn0IuXrskhkBVHYrv76BgNAX6lYJn7PVQSwW2Fh/YqaDkXtZnm7d+sySnY+cGaDS4efLV6OxnvcjY7vAF4MtGDTPrvw3Mn3twa6popvPjOmdU76xtYC40Ahfq2ddt1OSFetj5MU/OAKaVJDAmuQV/1US/aStCM1SyeqSpzMOlhRkvBh+Li3/UlLiCgdYjTyO6l7CGcNr6qrEf0T9/4CJ3anI/ddFpbUU/xNxseqlHzT0YZk=
  - GH_REF: github.com/womenwhocodedc/womenwhocodedc.github.io.git
