dist: trusty

before_install:
  - wget https://github.com/gohugoio/hugo/releases/download/v0.25.1/hugo_0.25.1_Linux-64bit.deb
  - sudo dpkg -i hugo_0.25.1_Linux-64bit.deb

script:
  - ./deploy.sh

env:
  global:
  - GH_REF: github.com/womenwhocodedc/womenwhocodedc.github.io.git
